language: generic
sudo: required
dist: xenial
 
addons:
  apt:
    packages:
      - fastd
script:
 - for f in *; do echo "checking $f..."; fastd --verify-config --config-peer $f || exit 1; done

branches:
  except:
    - deploy
    - github-action

notifications:
  email:
    recipients:
      - post@0x21.biz
      - oleander@oleander.cc
      - manu@dreivirteileins.de
    on_success: change
    on_failure: change
  irc:
    channels:
      - "irc.hackint.org#hsmr"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: false
  webhooks:
    urls:
      - http://api.marburg.freifunk.net/yolokey/deploy
    on_success: always
    on_failure: never
    on_start: never
